name: Build Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # fallback filter if the push filter above isn’t available
    if: "!contains(github.event.head_commit.message, 'chore')"

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - run: npm ci

    - run: node ./scripts/pre.ts

    - run: npm run build --if-present

    - name: Zip dist folder
      run: zip -r dist.zip dist

    - name: Upload dist artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist.zip
